version: '3.9'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:10.15
      volumes:
        - ./postgre/data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      deploy:
        resources:
          limits:
            cpus: 0.30
            memory: 512m
  keycloak:
#      image: quay.io/keycloak/keycloak:20.0.2
      build: .
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_PORT: 5432
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KC_LOG_LEVEL: info
        KC_HOSTNAME: localhost
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_FEATURES_DISABLED: "impersonation, update-email"
        KC_TZ: "Asia/Jakarta"
        DEBUG_PORT: "*:8787"
      volumes:
        - ./providers:/opt/keycloak/providers
        - ./imports:/opt/keycloak/imports
      ports:
        - "8080:8080"
        - "8443:8443"
        - "8787:8787"
#      command: start-dev --debug
      command: start --optimized --debug
      logging:
        options:
          max-size: "1m"
          max-file: "1"
      deploy:
        resources:
          limits:
#            cpus: 0.30
            memory: 512m
      depends_on:
        - postgres
